### ISSUE TITLE
[M0] ¿Qué es un plato?

### ISSUE THREAD

**Issue by MarioRgzLpz** [antoniorr02/MenuConsulter#11]
Según las HUs (#4, #5) vamos a mostrar-filtrar platos relacionados con menús, asociados a un comedor pero, ¿qué es un plato? ¿Es simplemente un conjunto de ingredientes?

**Comment by JJ** [comment]
¿Qué tiene que ver esto con #6?

**Comment by MarioRgzLpz** [comment]
> ¿Qué tiene que ver esto con #6?

En #6 hablamos de que queremos filtrar los platos por objetivos nutricionales, por lo que la estructura de los platos debe reflejar esto, aunque siendo concisos este issue se debería de tratar en un milestone más avanzado puesto que esta funcionalidad no va a ser añadadida hasta el milestone 3.

**Comment by JJ** [comment]
En general, si un issue se refiere a dos historias de usuario o no es un buen issue o las historias de usuario no se han dividido adecuadamente.

**Comment by JJ** [comment]
> > ¿Qué tiene que ver esto con #6?
> 
> En #6 hablamos de que queremos filtrar los platos por objetivos nutricionales, por lo que la estructura de los platos debe reflejar esto, aunque siendo concisos este issue se debería de tratar en un milestone más avanzado puesto que esta funcionalidad no va a ser añadadida hasta el milestone 3.

¿Y si no se fijan los objetivos nutricionales no es un plato? Eso es lo que pregunta aquí.

El problema, insisto, es trabajar con *todas* las historias de usuario. Si has secuenciado el problema en historias de usuario, pero luego tienes que trabajar con *todas*, ¿para qué lo haces?

Te recuerdo que no estás obligado a trabajar con todas las HUs si ves que algunas no están relacionadas o no te permiten crear un modelo mínimo. En este caso además los aportes nutricionales ni siquiera se van a poder abordar dentro de esta asignatura, simplemente porque no se trata de eso el proyecto. Si es necesario, @antoniorr02 , reescribe los milestones y quita lo que no sea necesario.
