### ISSUE TITLE
¿Con qué lenguaje de programación queremos trabajar?

### ISSUE THREAD

**Issue by MarioRgzLpz** [antoniorr02/MenuConsulter#7]
Para saber que lenguaje de programación será el más adecuado tendremos que hacernos dos preguntas:

- ¿Qué lenguaje de programación es el más adecuado para el proyecto?
- ¿Es el lenguaje de programación cómodo para los desarrolladores?

Vamos a ver que lenguaje se adecúa más al proyecto.

**Comment by MarioRgzLpz** [comment]
Para poder contestar antes es necesario saber como sería la aplicación desarrollada en el futuro. Voy a proporcionar algunos lenguajes que, a mi parecer, podrían encajar con el proyecto.

-¿Va a ser una aplicación movil, web o de escritorio? En caso de que sea una aplicación movil podríamos usar Java o Kotlin(Este esta especializado en desarrollo movil). Si fuese web tendría sentido usar algun lenguaje como JavaScript y para aplicación de escritorio se podría usar Go un lenguaje _similar_ a Python pero más moderno, Ruby o el propio Python (aunque todos permiten hacer multiples tipos de aplicaciones).

- ¿Es necesario un alto rendimiento en la aplicación? Si fuese el caso, convendría usar lenguajes de más bajo nivel con los que obtendríamos mejores resultados como puede ser C++, Rust o similares. Para nuestro caso como es para hacer scripting y mostrar unos datos, de manera no muy urgente, no sería necesario un lenguaje que nos ofrezca un alto rendimiento y simplemente nos bastaría con uno más sencillo y intuitivo.

**Conclusión:** Por facilidad eligiriamos Python puesto que tiene librerias para prácticamente cualquier cosa, pero usar cualquiera de los otros no es mala decisión. En lo personal, puede ser más entretenido cambiar del ya muy visto Python.

**Comment by antoniorr02** [comment]
Me parece bastante interesante la propuesta de Go, además de por no haberlo utilizado nunca, por las recomendaciones que el tutor dio sobre el mismo.
Además, en el repositorio de mi compañero parece que este va a ser el lenguaje elegido, con lo que podría unificar el aprendizaje del mismo con ambos proyectos.

Si te parece bien podríamos utilizar este para el desarrollo de la aplicación.

**Comment by MarioRgzLpz** [comment]
Perfecto, así también aprendo algo de `Go`, ya que he tenido muy poco contacto con él.
